name: Auto Merge PRs

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install actionlint
        run: |
          curl -sSfL https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash \
            | bash -s -- latest /usr/local/bin

      - name: Run actionlint
        run: actionlint

  merge:
    needs: tests
    uses: ./.github/workflows/workflow-merge-pull-requests.yml
    permissions:
      contents: write
      pull-requests: write
    with:
      target-branch: main
      pull-requests: ${{ toJson(github.event.pull_request) }}
    secrets:
      gh_token: ${{ secrets.GITHUB_TOKEN }}
